# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/osx-64/bzip2-1.0.8-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/c-ares-1.17.1-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2021.7.5-hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2021.3.0-hecd8cb5_3375.conda
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9d-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-12.0.0-h2f01273_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libev-4.33-h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libiconv-1.16-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-base-1.2.0-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/llvm-openmp-12.0.0-h0dcd299_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2021a-h5d7bf9c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/utf8proc-2.6.1-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/abseil-cpp-20210324.2-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/aws-c-common-0.4.57-hb1e8313_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/brotli-1.0.9-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/double-conversion-3.1.5-haf313ee_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/gflags-2.2.2-h0a44026_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/icu-58.2-h0a44026_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.3-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libprotobuf-3.17.2-h2842e9f_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/lz4-c-1.9.3-h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-2021.3.0-hecd8cb5_517.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.2-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1l-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/re2-2020.11.01-h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/snappy-1.1.8-hb1e8313_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.11-h7bc2e8c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/uriparser-0.9.3-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/aws-checksums-0.1.9-hb1e8313_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.10.4-ha233b18_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/glog-0.5.0-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/grpc-cpp-1.39.0-h8dc0301_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/libedit-3.1.20210714-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libevent-2.1.8-hddc9c9b_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libnghttp2-1.41.0-h7580e61_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libssh2-1.9.0-ha12b0ac_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.1-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.4.9-h322a384_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/aws-c-event-stream-0.1.6-h23ab428_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/krb5-1.19.2-hcd88c3b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libboost-1.73.0-hd4c2dcd_11.conda
https://repo.anaconda.com/pkgs/main/osx-64/libthrift-0.14.2-h054ceb0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libtiff-4.2.0-h87d7836_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/orc-1.6.9-h2519b9b_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.36.0-hce871da_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/boost-cpp-1.73.0-h9ed2024_11.conda
https://repo.anaconda.com/pkgs/main/osx-64/lcms2-2.12-hf1fd2bf_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcurl-7.78.0-hb8e4fae_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/openjpeg-2.4.0-h66ea3da_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/python-3.9.7-h88f2d9e_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/qt-5.9.7-h468cd18_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/appnope-0.1.2-py39hecd8cb5_1001.conda
https://repo.anaconda.com/pkgs/main/osx-64/aws-sdk-cpp-1.8.185-he271ece_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2021.5.30-py39hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.3.1-py39h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/olefile-0.46-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/py4j-0.10.9.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.9-2_cp39.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/sip-4.19.13-py39h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.1-py39h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/traitlets-5.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/cycler-0.10.0-py39hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jedi-0.18.0-py39hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/matplotlib-inline-0.1.2-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-service-2.4.0-py39h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/pillow-8.3.1-py39ha4cf6ea_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.17-pyhca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyqt-5.9.2-py39h23ab428_6.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-58.0.4-py39hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.20.3-py39he0bd621_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-21.2.4-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.10.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ipython-7.27.0-py39h01d92e1_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/arrow-cpp-3.0.0-py39ha6b1260_4.conda
https://repo.anaconda.com/pkgs/main/osx-64/bottleneck-1.3.2-py39he3068b8_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-3.4.2-py39hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.4.2-py39h8b3ea08_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.3.0-py39h4a7008c_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.2.2-py39hb2f4e1b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.20.3-py39h4b4dc7a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numexpr-2.7.3-py39h5873af2_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/scipy-1.7.1-py39h88652d9_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/pandas-1.3.3-py39h5008ddb_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/scikit-learn-0.24.2-py39hb2f4e1b_0.conda
https://conda.anaconda.org/conda-forge/noarch/imbalanced-learn-0.8.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyarrow-3.0.0-py39hdf3e9eb_3.conda
https://repo.anaconda.com/pkgs/main/noarch/seaborn-0.11.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyspark-3.1.2-pyhd3eb1b0_0.conda
